# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_simpleslider', '0002_auto_20150730_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_simpleslider_slider', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
