# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_simpleslider', '0003_auto_20160819_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='infinite',
            field=models.BooleanField(default=False, verbose_name='Infinite'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slides_to_scroll',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Slides to scroll'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slides_to_show',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Slides to show'),
        ),
    ]
